require: 'rubocop-performance'

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'bin/*'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/initializers/content_security_policy.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'config/initializers/wrap_parameters.rb'
    - 'config/puma.rb'
    - 'db/schema.rb'
    - 'lib/templates/**/*.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.6

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'

Metrics/BlockLength:
  Exclude:
    - 'config/**/*.rb'
    - 'lib/**/*.rake'
    - 'Guardfile'
    - 'Rakefile'
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'app/dashboards/*'

Metrics/LineLength:
  Exclude:
    - 'app/dashboards/*'
    - 'config/initializers/*'
    - 'db/migrate/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Naming/FileName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/IfUnlessModifier:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/WordArray:
  EnforcedStyle: brackets
